// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "ad (1).jpg",
        "revision": "417b73c18c683e9674348d2b9a6cf5bc"
    },
    {
        "url": "ad (10).jpg",
        "revision": "396050c34e7329a212fbd6c2eb04ee28"
    },
    {
        "url": "ad (11).jpg",
        "revision": "96aef130f8126e421d401681d4035f53"
    },
    {
        "url": "ad (12).jpg",
        "revision": "40054beaa18b2eac0c9a6c639e10b33c"
    },
    {
        "url": "ad (13).jpg",
        "revision": "69fe44ffa38f4a3016f2137320ffbd2b"
    },
    {
        "url": "ad (14).jpg",
        "revision": "316497f0a052115dc83261abf4f05ab7"
    },
    {
        "url": "ad (15).jpg",
        "revision": "7742ec990b0aa1b83a2a45efb7a54212"
    },
    {
        "url": "ad (2).jpeg",
        "revision": "26b318b4f1653e7de4f28ef2bc7ba3a6"
    },
    {
        "url": "ad (2).jpg",
        "revision": "e17eac46e828f7b8ba856e57b8db61fe"
    },
    {
        "url": "ad (3).jpg",
        "revision": "3e32912d82c45d9de98349de4d9586ae"
    },
    {
        "url": "ad (4).jpg",
        "revision": "629da8bd77697af5e7b060d625980673"
    },
    {
        "url": "ad (5).jpg",
        "revision": "34c87ff7f684dd591caa7fe727acc04c"
    },
    {
        "url": "ad (6).jpg",
        "revision": "0bfca688699d483ea2be5fcfb40f4787"
    },
    {
        "url": "ad (7).jpg",
        "revision": "e37e5dff5e7b82e54f832bd4ff5e81ac"
    },
    {
        "url": "ad (8).jpg",
        "revision": "a6d1c5204f8b027aa0819c6dcf0c33dc"
    },
    {
        "url": "ad (9).jpg",
        "revision": "f6a2d6f098eb64564c7daa7f89891673"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "copilot.html",
        "revision": "f925dff68e9513f3c924dc2538b635f2"
    },
    {
        "url": "google.html",
        "revision": "e6b07b918c6b3a053f8a01230dd4b4b0"
    },
    {
        "url": "grok.html",
        "revision": "b20b392e6477b5879db5d00d878f2a25"
    },
    {
        "url": "index.html",
        "revision": "aa9fe335be61db2bda0a4a4b4399a881"
    },
    {
        "url": "indexw.html",
        "revision": "2d9b3c96a7e3562d7498abae1d588ddb"
    },
    {
        "url": "islamic-poster-1771325096068.png",
        "revision": "006556dc8a5f42da703a4ecb4657ebee"
    },
    {
        "url": "islamic-poster-1771325357018.png",
        "revision": "2cf65b3042a0c850a3452ca5cdda516b"
    },
    {
        "url": "islamic_poster_creator (1).html",
        "revision": "94ad945bcfbc76d37274d384a8df993b"
    },
    {
        "url": "islamic_poster_creator.html",
        "revision": "1fe84b143e8a00d4517928413568056c"
    },
    {
        "url": "islamic_poster_premium.html",
        "revision": "a6e28f82e2fbfab66c527e4657577eb5"
    },
    {
        "url": "jamia-admission-editor.html",
        "revision": "2ef20912890f9fd9f22be4f56e418c2b"
    },
    {
        "url": "madrasa-flyer-1771324637171.png",
        "revision": "d7ddfe56920ef5bf18adb9be264729f0"
    },
    {
        "url": "madrasa-flyer-editor.html",
        "revision": "f8b644dec494616a7bf614be5310907d"
    },
    {
        "url": "new.html",
        "revision": "4a56e6780e09380d30e9a37a4a461403"
    },
    {
        "url": "offline.html",
        "revision": "7656c61e25225c4fcc77cb000be6d527"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}