// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "ad (1).jpg",
        "revision": "417b73c18c683e9674348d2b9a6cf5bc"
    },
    {
        "url": "ad (10).jpg",
        "revision": "396050c34e7329a212fbd6c2eb04ee28"
    },
    {
        "url": "ad (11).jpg",
        "revision": "96aef130f8126e421d401681d4035f53"
    },
    {
        "url": "ad (12).jpg",
        "revision": "40054beaa18b2eac0c9a6c639e10b33c"
    },
    {
        "url": "ad (13).jpg",
        "revision": "69fe44ffa38f4a3016f2137320ffbd2b"
    },
    {
        "url": "ad (14).jpg",
        "revision": "316497f0a052115dc83261abf4f05ab7"
    },
    {
        "url": "ad (15).jpg",
        "revision": "7742ec990b0aa1b83a2a45efb7a54212"
    },
    {
        "url": "ad (2).jpeg",
        "revision": "26b318b4f1653e7de4f28ef2bc7ba3a6"
    },
    {
        "url": "ad (2).jpg",
        "revision": "e17eac46e828f7b8ba856e57b8db61fe"
    },
    {
        "url": "ad (3).jpg",
        "revision": "3e32912d82c45d9de98349de4d9586ae"
    },
    {
        "url": "ad (4).jpg",
        "revision": "629da8bd77697af5e7b060d625980673"
    },
    {
        "url": "ad (5).jpg",
        "revision": "34c87ff7f684dd591caa7fe727acc04c"
    },
    {
        "url": "ad (6).jpg",
        "revision": "0bfca688699d483ea2be5fcfb40f4787"
    },
    {
        "url": "ad (7).jpg",
        "revision": "e37e5dff5e7b82e54f832bd4ff5e81ac"
    },
    {
        "url": "ad (8).jpg",
        "revision": "a6d1c5204f8b027aa0819c6dcf0c33dc"
    },
    {
        "url": "ad (9).jpg",
        "revision": "f6a2d6f098eb64564c7daa7f89891673"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "copilot.html",
        "revision": "ccc8f9ec1c269ee4952cae8b10df026e"
    },
    {
        "url": "google.html",
        "revision": "fc7f4296c9815b87538f30052981b219"
    },
    {
        "url": "grok.html",
        "revision": "e2ac58d5bb61355409f6cc093cf7322e"
    },
    {
        "url": "index.html",
        "revision": "254683433b9ffb18e72584823ef9b7ea"
    },
    {
        "url": "indexw.html",
        "revision": "1aa0f645e639454ddf356b789badbe51"
    },
    {
        "url": "islamic-poster-1771325096068.png",
        "revision": "006556dc8a5f42da703a4ecb4657ebee"
    },
    {
        "url": "islamic-poster-1771325357018.png",
        "revision": "2cf65b3042a0c850a3452ca5cdda516b"
    },
    {
        "url": "islamic-poster-1771325596596.png",
        "revision": "eaaebe33d7d86ca65e9853aff9b86ebd"
    },
    {
        "url": "islamic_poster_creator (1).html",
        "revision": "ed2261a05fd9d35ec2d61b2405718425"
    },
    {
        "url": "islamic_poster_creator.html",
        "revision": "a4c263b54f0e9cbd616ed4144dda3024"
    },
    {
        "url": "islamic_poster_premium.html",
        "revision": "0369a1d88539521587fde7339033a8ad"
    },
    {
        "url": "jamia-admission-editor.html",
        "revision": "bc3622a5db2d534193882c7634b52631"
    },
    {
        "url": "madrasa-flyer-1771324637171.png",
        "revision": "d7ddfe56920ef5bf18adb9be264729f0"
    },
    {
        "url": "madrasa-flyer-editor.html",
        "revision": "a1c39e36d4ae6fc08ccaa456a046f4cd"
    },
    {
        "url": "manifest.json",
        "revision": "358b1fba18149fce96b66c26eb70ad26"
    },
    {
        "url": "new.html",
        "revision": "1b3f9bdb8944ccb344c1c4ae27729908"
    },
    {
        "url": "offline.html",
        "revision": "93dd8135f88165fc1bbc0acf525cd1d3"
    },
    {
        "url": "sw.js",
        "revision": "c3f0b0ecedb1b8f4a63cf0bf7cac1591"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}